language: r

r:
  - devel
  - release

sudo: false

cache: packages

github_packages:
  - assertthat
  - devtools

r_check_args: --as-cran

notifications:
  email:
    recipients:
      - laurence.brandenberger@eawag.ch
    on_success: change
    on_failure: change
